### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by turkeyaa** [skelpo/JWTAuthExample#2]
Thread 1: Fatal error: Error raised at top level: ⚠️ JWTProviderError: No 'JWT_SECRET' environment variable was found
How to solve？

**Comment by proggeramlug** [comment]
Do you have a JWT secret? It is part of the JWT that is used to verify the data in the payload. 

When you have one just pass it along as an environment variable. In Mac/Linux it works like this:
"export JWT_SECRET=...."

Is that making sense? :)

**Comment by turkeyaa** [comment]
OK. Thanks
