### ISSUE TITLE
Crypto error

### ISSUE THREAD

**Issue by santi-d** [skelpo/JWTAuthExample#4]
Hi, please can you help me with this issue?

I think that the error is the way I am creating JWT PUBLIC and PRIVATE value, I am using default values from another project yours, but reading I think I must create a valid values for these String, can you confirm to me if my thoughts are right, or not, and maybe you can share with me the right way to create them.

Thanks

[ ERROR ] CryptoError.rsaSign: RSA signature creation failed: unknown. (/Users/nuss/Downloads/JWTAuthExample-master/.build/checkouts/vapor.git-5492988889259800272/Sources/Vapor/Logging/Logger+LogError.swift:17)

**Comment by proggeramlug** [comment]
Hi @focker321 ,

sorry for the super delayed response. I'm not quite sure I understand your problem - can you help me reproduce it somehow?

Best,
Ralph

**Comment by santi-d** [comment]
Hi @proggeramlug I was be able to fix that estrange error, it was because I required a public and secret cert, created with OpenSSL, the only difficult thing is create the content variable, I am using some tricks to load that content in environment variable. Thanks, you can close the Issue

**Comment by proggeramlug** [comment]
Glad to hear that, let me know if you have any other issues! :)
